const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('crimeGPT', {

  checkSetup: () => ipcRenderer.invoke('auth:check-setup'),
  setupAdmin: (username, password) => ipcRenderer.invoke('auth:setup-admin', username, password),
  login: (username, password) => ipcRenderer.invoke('auth:login', username, password),
  checkAISetup: () => ipcRenderer.invoke('ai:check-setup'),
  installOllama: () => ipcRenderer.invoke('ai:install-ollama'),
  downloadModel: () => ipcRenderer.invoke('ai:download-model'),
  downloadEmbedModel: () => ipcRenderer.invoke('ai:download-embed-model'),
  startOllama: () => ipcRenderer.invoke('ai:start-ollama'),
  onAIProgress: (callback) => ipcRenderer.on('ai:download-progress', (_, data) => callback(data)),
  aiChat: (message) => ipcRenderer.invoke('ai:chat', message),
  getLegalSuggestion: (fir) => ipcRenderer.invoke('ai:legal-suggestion', fir),
  getEmbedding: (text) => ipcRenderer.invoke('ai:embedding', text),
  getLegalSuggestionRAG: (fir) => ipcRenderer.invoke('rag:legal-suggestion', fir),
  searchSimilarCases: (query) => ipcRenderer.invoke('rag:search-similar-cases', query),
  searchLaws: (query) => ipcRenderer.invoke('rag:search-laws', query),
  registerCase: (data) => ipcRenderer.invoke('case:register', data),
  getFullCase: (caseId) => ipcRenderer.invoke('case:get-full', caseId),
  generateFIRNumber: () => ipcRenderer.invoke('case:generate-fir-number'),
  getAllCases: () => ipcRenderer.invoke('case:get-all'),
  searchCases: (query) => ipcRenderer.invoke('case:search', query),
  addDiaryEntry: (data) => ipcRenderer.invoke('diary:add', data),
  getCaseDiary: (caseId) => ipcRenderer.invoke('diary:get', caseId),
  getStats: () => ipcRenderer.invoke('dashboard:stats'),
  saveAsPDF: (html, filename) => ipcRenderer.invoke('doc:save-as-pdf', html, filename),
  suggestSections: (query) => ipcRenderer.invoke('ai:suggest-sections', query),
  getDocsForCase: (caseId) => ipcRenderer.invoke('doc:get-for-case', caseId),
generateDocument: (caseId, docKey, caseData) => ipcRenderer.invoke('doc:generate', caseId, docKey, caseData),
saveDocRecord: (caseId, docType, docName, docPath) => ipcRenderer.invoke('doc:save-record', caseId, docType, docName, docPath),
onDownloadComplete: (callback) => ipcRenderer.on('download-complete', (_, data) => callback(data)),
sendLERS: (data) => ipcRenderer.invoke('lers:send', data),
getLERSForCase: (caseId) => ipcRenderer.invoke('lers:get-for-case', caseId),
getBharatPolCriminals: (params) => ipcRenderer.invoke('bharatpol:get-criminals', params),
syncBharatPolCase: (data) => ipcRenderer.invoke('bharatpol:sync-case', data),
shareBharatPolCase: (data) => ipcRenderer.invoke('bharatpol:share-case', data),
getAuditLog: (caseId) => ipcRenderer.invoke('audit:get-for-case', caseId),
updateCaseAccused: (caseId, accused) => ipcRenderer.invoke('case:update-accused', caseId, accused),
});